name: Docker Build/Publish Image

on:
  push:
    branches: [production]
    paths-ignore:
      - README.md
      - .trunk
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get current date
        run: echo "DATE=$(date +'%Y.%m.%d')" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ env.DATE }}-${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Create a Release
        uses: elgohr/Github-Release-Action@edea2b66b44cdd48a00eb134b39959db2703b1cd # 20240405193535
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Release ${{ env.DATE }}"

      - name: Send Discord notification
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1
        if: always()
        with:
          title: "Build image on ${{ github.repository }}: ${{ github.workflow }}"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
